### ISSUE TITLE
[BUG]: Advanced Checkout React Integration fails to render with successful token from generateClientToken; throws Braintree Integration error

### ISSUE THREAD

**Issue by mckinlde** [paypal/react-paypal-js#410]
<snip; please delete--the option is disabled for e>

**Comment by mckinlde** [comment]
So far, I've been able to verify:
**server.js**
- generateAccessToken() returns a valid token in this format:
`{
  scope: 'https://uri.paypal.com/services/checkout/one-click-with-merchant-issued-token https://uri.paypal.com/services/invoicing https://uri.paypal.com/services/vault/payment-tokens/read https://uri.paypal.com/services/disputes/read-buyer https://uri.paypal.com/services/payments/realtimepayment https://uri.paypal.com/services/disputes/update-seller https://uri.paypal.com/services/payments/payment/authcapture openid https://uri.paypal.com/services/disputes/read-seller Braintree:Vault https://uri.paypal.com/services/payments/refund https://api.paypal.com/v1/vault/credit-card https://uri.paypal.com/services/pricing/quote-exchange-rates/read https://uri.paypal.com/services/billing-agreements https://api.paypal.com/v1/payments/.* https://uri.paypal.com/services/vault/payment-tokens/readwrite https://api.paypal.com/v1/vault/credit-card/.* https://uri.paypal.com/services/shipping/trackers/readwrite https://uri.paypal.com/services/applications/webhooks',
  access_token: 'redacted',
  token_type: 'Bearer',
  app_id: 'redacted',
  expires_in: 31736,
  nonce: 'redacted'
}`

- generateClientToken returns a token in this format:
`{
  client_token: 'redacted',
  expires_in: 3600
}`
**App.jsx**
- the token returned by generateClientToken is sent to the browser and used to update the state variable `setClientToken(client_token);`

At this point the err is thrown and the page does not render.  Checking my account/app, the PayPal dashboard shows "account type: business" and "You've been approved for Advanced Checkout".

I suspected a problem with cors against my server, but because I'm able to print the token in my browser console I know that it is being set in the state variable.  I can also see in the browser's local storage a value '__paypal_storage__' of the format:
`{
id: "redacted",
__session__: {guid: "redacted", created: redacted}
}`

The [integration builder](https://developer.paypal.com/integration-builder/) code examples are linked to by the [page](https://www.paypal.com/merchantapps/setup/checkout/advanced) that shows my API credentials, which is in turn linked by the tile showing 'You've been approved for advanced checkout' on my [dashboard](https://www.paypal.com/mep/dashboard).

Notably, the integration builder page shows a 'Last updated: November 29 2023, 11:06:09 am', which is <15m ago as of this post.

Have I stumbled upon an active development project at PayPal?  Are you hiring?

**Comment by mckinlde** [comment]
It appears that the state variable is not updating, despite valid response from the server:

**App.js**
`useEffect(() => {
    (async () => {
      const response = await fetch("/api/token", {
        method: "POST",
      });
      const { client_token } = await response.json();
      console.log('client_token: ',client_token)
      setClientToken(client_token);
      console.log('clientToken: ', clientToken); // added logging to verify token is returned
    })();
  }, []);`
  
  **Browser Console:**
`PaypalView.jsx:23 client_token:  redacted
PaypalView.jsx:25 clientToken:  null`

**Comment by mckinlde** [comment]
> It appears that the state variable is not updating, despite valid response from the server:

Nope; the stateVariable updates just fine after useEffect finishes:

**App.js (refactored to define/call fetchClientToken() function outside/inside useEffect()**

`async function fetchClientToken() {
    const response = await fetch("/api/token", {
      method: "POST",
    });
    const resp = await response.json();
    console.log('client_token: ',resp.client_token)
    //return resp.client_token
    setClientToken(resp.client_token);
  }

  useEffect(() => {
    fetchClientToken()
  }, []);

  console.log('clientToken after useEffect: ',clientToken);`

**browser console**

`clientToken after useEffect:  undefined
PaypalView.js:22 client_token:  redacted
PaypalView.js:31 clientToken after useEffect:  redacted
PaypalView.js:31 clientToken after useEffect:  redacted
react-dom.production.min.js:189 Error: Invalid authorization data. Use dataClientToken or dataUserIdToken to authorize.
    at react-paypal-js.js:323:11
    at ey (react-paypal-js.js:357:23)
    at dy (react-paypal-js.js:1176:12)
    at _i (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at ws (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at is (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
du @ react-dom.production.min.js:189
a.componentDidCatch.n.callback @ react-dom.production.min.js:190
La @ react-dom.production.min.js:144
xl @ react-dom.production.min.js:261
wl @ react-dom.production.min.js:260
bl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
ks @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14
hooks.tsx:610 React Router caught the following error during render Error: Invalid authorization data. Use dataClientToken or dataUserIdToken to authorize.
    at react-paypal-js.js:323:11
    at ey (react-paypal-js.js:357:23)
    at dy (react-paypal-js.js:1176:12)
    at _i (react-dom.production.min.js:167:137)
    at _l (react-dom.production.min.js:290:337)
    at ws (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at is (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429) {componentStack: '\n    at dy (https://singlepaynews.com/static/js/ma…om/static/js/main.784eb097.js:2:455304)\n    at jy'}
value @ hooks.tsx:610
a.componentDidCatch.n.callback @ react-dom.production.min.js:190
La @ react-dom.production.min.js:144
xl @ react-dom.production.min.js:261
wl @ react-dom.production.min.js:260
bl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
ks @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
k @ scheduler.production.min.js:13
P @ scheduler.production.min.js:14`
